### ISSUE TITLE
[bug] Next selection drops after deleting line

### ISSUE THREAD

**Issue by rusak47** [lkosson/gced#1]
Hello! Thank you for developing and sharing this cool editor. While it's simple, it allows for the graphical editing of G-code.

I haven't found any editor where you can select multiple plotted lines and easily delete them (a nice feature would be to allow commenting them, and splitting a line). 
However, when deleting plotted lines, I encounter **a bug** where the **next selection gets reset after every delete action**. This means that after every delete, I'm forced to select the next line twice.
https://github.com/lkosson/gced/assets/8426197/2ba4f349-5ab5-49d5-8acc-91e8c22972d3

It's important to note that i'm running the editor in wine 4.0 on Ubuntu 22.04.

**Comment by lkosson** [comment]
Hi. Indeed selection doesn't work as intended when deleting multiple elements. I have fixed that. I'll work on your other suggestions as well - stay tuned for an update in a few days.

**Comment by lkosson** [comment]
I have published a 1.2.1 release which fixes selection resetting after deleting a line and adds action to comment/uncomment selected lines.

As for line splitting - if you have a line selected, use `1` (or `Insert` -> `Line`) to create a new line from the beginning of selected line to a new point. Selected line then gets fixed up to go from new point to the previous destination - regardless of `G90` / `G91` mode. This effectively splits a line.

**Comment by rusak47** [comment]
It's almost perfect, however this nasty bug still occurs. (after 2min)

Additionally, in this clip you can notice:
 - a problem with snapping: with a small distance between lines it's hard to snap to grid (starting from 7th min).
 - (enhancement) there is no move view action, which is useful for zoom. Maybe a selection between "select" and "move" modes or attach it to left mouse button which doesn't do anything right now. (starting from 9th min) and there happened a bug - zoom centered on selected vector after i pressed ESC to cancel insert (but it's more like a good bug :) ).
 - gcode text column doesn't have vertical slider (but maybe it's because of wine).


https://github.com/lkosson/gced/assets/8426197/b49b7441-e1cd-44a3-ba58-898940d60bc1
[head.nc](https://pastebin.com/BxArDiSL)

**Comment by lkosson** [comment]
* At 2:02, when you delete multiple lines, as far as I can tell next line after 372 line `G1 X50.0655 Y108.2173` is selected correctly. It happens to be `M5` line which corresponds to no visual item on canvas, but it's still selected.
 * At 7:20 selected menu items didn't get recorded to video, but it looks like you have snapping to other items enabled. To be honest, the whole snapping mechanism is a bit quirky right now and needs a proper rework.
 * You can pan the view using middle mouse button.
 * There is no vertical slider in gcode listing, but you can resize whole right panel by dragging a splitter between the panel and canvas.

**Comment by rusak47** [comment]
> * At 2:02, when you delete multiple lines, as far as I can tell next line after 372 line `G1 X50.0655 Y108.2173` is selected correctly. It happens to be `M5` line which corresponds to no visual item on canvas, but it's still selected.

You are correct. I wasn't precise enough, and I apologize for that.

Please take a look at 2:18 in the video. I select the first vector `G1 X57.0655 Y104.2173` in the visual editor, and then I attempt to select the line `G0 X57.0655 Y100.2173`, but the editor resets to the beginning. This issue occurs multiple times in the video.

> * At 7:20 selected menu items didn't get recorded to video, but it looks like you have snapping to other items enabled. To be honest, the whole snapping mechanism is a bit quirky right now and needs a proper rework.

Sorry for the inconvenience. The recording software ignores them. I've tried all possible variations, and "Snap to axis" only worked, but in the video, it doesn't snap to anything. It seems to ignore everything, making it easy to place a point. But this is not a big deal.

> * You can pan the view using middle mouse button.

Good to know, but the problem is that I don't own a mouse with that capability. In fact, I'm working with a TV box keyboard that has an integrated gyroscope. I believe there should be an alternative way for users like me, such as a keyboard shortcut or clicking both mouse buttons (L+R).

> * There is no vertical slider in gcode listing, but you can resize whole right panel by dragging a splitter between the panel and canvas.

i've tried that, but it doesn't help.
[no_sliding_bar_resize.webm](https://github.com/lkosson/gced/assets/8426197/ecb17015-2e00-430d-ae83-92830e286bbd)

**Comment by lkosson** [comment]
Can you please describe what exactly did you do at 2:23? It looks like you just clicked on `G0` line and it did reset selection, but I can't reproduce that behavior in my environment. Does selecting single items from the list work at all on your system?

At 7:19-7:20 you can see endpoint jumping between two points of other operations, snapping to those points. "Snap to axes" helps creating horizontal/vertical lines. Holding `Shift` temporarily disables all snapping.

Good point about panning, especially on laptops. I have added `P` shortcut and menu item as an alternative.

As for vertical scrollbar - from your videos it looks like whole list is clipped at right. Most likely some issues with Mono and/or Wine. On Debian 12 (Wine 8) and Windows 7 looks fine - screenshot below. I'll try to check it on Ubuntu and/or older Wine, but no promises.
![gced](https://github.com/lkosson/gced/assets/22995707/200097ff-c251-4861-83b6-700093b5464e)

**Comment by rusak47** [comment]
> Can you please describe what exactly did you do at 2:23? It looks like you just clicked on `G0` line and it did reset selection, but I can't reproduce that behavior in my environment. Does selecting single items from the list work at all on your system?

Yes, selecting works most of the time. To reproduce this bug you need:
 1. delete some vector,
 2. select other vector in gui,
 3. select gcode in text editor <- this one will reset editor position

[bug_selectcode_after_selectvector_after_delete_reset.webm](https://github.com/lkosson/gced/assets/8426197/5942e5c1-a02d-4f5f-a2cc-0a8d9cf454d2)

**Comment by lkosson** [comment]
I see. Still, repeating your steps exactly I can't reproduce the behavior. Does it also happen when in last step you select line other than first? Also check if selection resets when you press or when you release button. I suspect it might something to do with how Wine handles those event in listbox.

**Comment by rusak47** [comment]
Okay, I'd better update Wine and check if it happens there.

**Comment by rusak47** [comment]
The latest Wine version, `8.16-40-ga240d380856`, fixed the problem with the scrollbar, but the bug hasn't disappeared. In fact, it occurs not only after deletion but also after insertion. The selection reset triggers instantly on pressing.

[screen-recorder-tue-sep-19-2023-17-40-32.webm](https://github.com/lkosson/gced/assets/8426197/98869b07-3079-4d6e-a9a7-1b3ba8de7c2b)

* It seems that step 2 is unnecessary. I can reproduce this reset without it, at least.

**Comment by lkosson** [comment]
Yep, that's not good at all. I'm still trying to reproduce it on my end.

**Comment by rusak47** [comment]
> Yep, that's not good at all. I'm still trying to reproduce it on my end.

If you don't succeed, I'll try to set up MonoDevelop on Ubuntu and then debug. Just point me to where I should check.

**Comment by lkosson** [comment]
I have installed a fresh QEMU VM with Wine and can now reproduce the behavior from your videos - operations list gets reset (scrolled to top) when selecting a line after deleting or modifying existing line.

**Comment by lkosson** [comment]
I think I have fixed it. Please extract and replace the attached file in your installation and see if it now works correctly. If it does, I'll publish a proper release.
[GCEd.zip](https://github.com/lkosson/gced/files/12680994/GCEd.zip)

**Comment by rusak47** [comment]
> I think I have fixed it. Please extract and replace the attached file in your installation and see if it now works correctly. If it does, I'll publish a proper release. [GCEd.zip](https://github.com/lkosson/gced/files/12680994/GCEd.zip)

Good job! With the new DLL, I can't reproduce this bug.

**Comment by lkosson** [comment]
Fixed in v1.2.2
